V2
TeamPGM/PagerMaid_Plugins pull request #6
Opened 2022-06-05 13:26 UTC by cloudreflection

## 该 PR 相关 Issue / Involved issue

上传一个新插件

## 插件名称 / Name

```
pmcaptcha
```

## 更改检查表 / Change Checklist
  
- [ ] 有插件版本号更新
- [x] 有多语言支持
  - [x] CN
  - [x] EN
- [ ] 会触发频率限制 Will trigger a rate limit?
  - [ ] 如果会, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] 添加了新的依赖包 New package added

## 说明 / Note
~~我又来了~~ 完善之后重新提交

2022-06-05 13:51 UTC, zhxycn commented on pmcaptcha/main.py
> +    import redis
Pagermaid_Pyro 的数据库使用 sqlite 而不使用 redis 。

2022-06-05 16:50 UTC, qwq233 requested changes

2022-06-05 16:50 UTC, qwq233 commented on pmcaptcha/main.py
> +        if cid==1148248480:
?
![image](https://user-images.githubusercontent.com/20317838/172061358-e9b83c35-b47f-46ea-899b-89e635cdd335.png)

2022-06-06 00:53 UTC, zhxycn commented on pmcaptcha/main.py
> +        if cid==1148248480:
夹带私货了（）

2022-06-06 06:48 UTC, cloudreflection commented on pmcaptcha/main.py
> +    import redis
现在是sqlite了（

2022-06-06 06:48 UTC, cloudreflection commented on pmcaptcha/main.py
> +    import redis
> Pagermaid_Pyro 的数据库使用 sqlite 而不使用 redis 。

现在是sqlite了（

2022-06-06 12:20 UTC, merged